name: First CICD

on: [push]

jobs:
  build:
  runs-on: ubuntu-latest

  strategy:
    matrix:
      python-version: [3.7,3.8]

  steps:
    - uses: actions/checkout@v3
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run Test
      run: |
        cd src
        python -m pytest addition.py
