name: Secret key
on:
  workflow_dispatch
env: 
      ACTIONS_STEP_DEBUG: true
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "checking the variable"
        run: |
          echo "Secret value is ${{ secrets.MY_KEY }}"
